name: C:\Users\atomar\AppData\Local\Continuum\Anaconda35\envs\gensim35
dependencies:
- mkl=11.3.3=1
- numpy=1.11.1=py35_0
- pip=8.1.2=py35_0
- python=3.5.2=0
- scipy=0.17.1=np111py35_1
- setuptools=23.0.0=py35_0
- vs2015_runtime=14.0.25123=0
- wheel=0.29.0=py35_0
- pip:
  - beautifulsoup4==4.4.1
  - boto==2.39.0
  - bs4==0.0.1
  - bz2file==0.98
  - gensim==0.10.2
  - httpretty==0.8.10
  - nltk==3.2.1
  - pandas==0.18.0
  - python-dateutil==2.5.2
  - pytz==2016.3
  - requests==2.8.1
  - scikit-learn==0.17.1
  - six==1.10.0
  - sklearn==0.0
  - smart-open==1.3.2

